name: CI

on:
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]
  
  workflow_dispatch:
    inputs:
      function_name:
        description: 'Function name (IfcColorizerTest, IfcColorizerStaging, IfcColorizerProd)'
        required: true,
        default: 'IfcColorizerTest'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: |
          ./build_deploy_package.ps1
        shell: pwsh

      - uses: actions/upload-artifact@v3
        with:
          name: ifc-colorizer
          path: ./ifc-colorizer.zip
  
  deploy_prod:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@master
        with:
          name: ifc-colorizer
      - name: Deploy to Lambda
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: ${{ github.event.inputs.function_name }}
          zip_file: ./ifc-colorizer.zip
          dry_run: false
